const REDUX_ACTION_TYPE = {
  SET_AUTH_USER: 'SET_AUTH_USER',
  UNSET_AUTH_USER: 'UNSET_AUTH_USER',
  RECEIVE_USERS: 'RECEIVE_USERS',
  SET_IS_PRELOAD: 'SET_IS_PRELOAD',
  RECEIVE_THREADS: 'RECEIVE_THREADS',
  ADD_THREAD: 'ADD_THREAD',
  TOGGLE_UPVOTE_THREAD: 'TOGGLE_UPVOTE_THREADS',
  ADD_COMMENT: 'ADD_COMMENT',
};

export default REDUX_ACTION_TYPE;
