const REDUX_ACTION_TYPE = {
  SET_AUTH_USER: 'SET_AUTH_USER',
  UNSET_AUTH_USER: 'UNSET_AUTH_USER',
  RECEIVE_USERS: 'RECEIVE_USERS',
  SET_IS_PRELOAD: 'SET_IS_PRELOAD',
};

export default REDUX_ACTION_TYPE;
